server.port=8080
spring.application.name=ms-stock

# Configuración MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/db_stock
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA y Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Para que los errores de @ControllerAdvice muestren el mensaje en Postman
server.error.include-message=always